### ISSUE TITLE
ArchLinux | gnome-mail not opening

### ISSUE THREAD

**Issue by sevachka** [davesteele/gnome-gmail#6] opened 2015-06-21 09:29 UTC
Hello,
since the last update, gnome-mail isn´t working any more. By starting it in terminal, I get the following output:

** (gnome-gmail:11110): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/bin/gnome-gmail", line 43, in <module>
    from gi.repository import Wnck
ImportError: cannot import name Wnck

Before the update it worked... 

Can you help me with this?

**Comment by davesteele** [comment] 2015-06-21 14:14
I don't know why the Wnck import is failing. Do  you have the package python-wnck installed?

**Comment by sevachka** [comment] 2015-06-21 16:00
after installing the python2-wnck (there was no python-wnck) I get the following error:
** (gnome-gmail:15127): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Traceback (most recent call last):
  File "/usr/bin/gnome-gmail", line 43, in <module>
    from gi.repository import Wnck
  File "/usr/lib/python2.7/site-packages/gi/importer.py", line 158, in load_module
    introspection_module = get_introspection_module(namespace)
  File "/usr/lib/python2.7/site-packages/gi/module.py", line 271, in get_introspection_module
    module = IntrospectionModule(namespace, version)
  File "/usr/lib/python2.7/site-packages/gi/module.py", line 120, in __init__
    repository.require(namespace, version)
gi.RepositoryError: Requiring namespace 'Gtk' version '2.0', but '3.0' is already loaded

I am using gnome-shell, so I guess it´s okay that GTK 3.0 is loaded?

**Comment by davesteele** [comment] 2015-06-21 18:01
GTK3 is required. I'd love to know what the conflict is.

**Comment by sevachka** [comment] 2015-06-21 18:12
Funny fact is, that it worked until the last update...

**Comment by max72bra** [comment] 2015-06-21 18:12
hi all, i'm the maintainer of archlinux gnome-gmail AUR package
please, can you post the output of: 'pacman -Qs wnck'
side note: python2-wnck is not a requirement and you can remove it
side note 2: if not, can you install libwnck3 package and give a try please?

**Comment by sevachka** [comment] 2015-06-21 18:15
pacman -Qs wnck gave back  "nothing".
After installing libwnck3 terminal output is as following:

** (gnome-gmail:18707): WARNING **: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.


BUT: now it is working. THANK YOU for your help. :) Arch rules! :)

**Comment by max72bra** [comment] 2015-06-21 18:18
great then. updating MY wrong deps list.
sorry dave, can close this as not a bug

**Comment by davesteele** [comment] 2015-06-21 20:35
Awesome. Thanks.

**Closed by davesteele** 2015-06-21 20:35 UTC
